/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import asymmetrictsp.GA;
import javax.swing.UIManager;
import part2.Part2;

/**
 *
 * @author Kenpachi
 */
public class GUI extends javax.swing.JFrame {
    Integer[] counters;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tspButton = new javax.swing.JButton();
        part2Button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultArea = new javax.swing.JTextArea();
        searchField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        stopField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        runField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Genetic Algorithms");
        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(51, 51, 51));
        setName("GUI"); // NOI18N
        setResizable(false);

        tspButton.setText("Assymetric Travelling Salesman");
        tspButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tspButtonActionPerformed(evt);
            }
        });

        part2Button.setText("Optimization of: x^2 + 16x ");
        part2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                part2ButtonActionPerformed(evt);
            }
        });

        resultArea.setBackground(new java.awt.Color(102, 102, 102));
        resultArea.setColumns(20);
        resultArea.setFont(new java.awt.Font("Dotum", 0, 12)); // NOI18N
        resultArea.setForeground(new java.awt.Color(255, 255, 255));
        resultArea.setRows(5);
        jScrollPane1.setViewportView(resultArea);

        searchField.setText("319");

        jLabel1.setText("Search For:");

        jLabel2.setText("Stop After:");

        stopField.setText("150000");

        jLabel3.setText("Amount of Runs:");

        runField.setText("100");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(stopField, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(searchField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tspButton, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(part2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(runField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tspButton)
                    .addComponent(part2Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(runField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(stopField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void part2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_part2ButtonActionPerformed
        int RUN_AMOUNT = Integer.parseInt(runField.getText());
        Part2 p2;
        counters = new Integer[RUN_AMOUNT];
        double sum=0;
        
        resultArea.setText("");
        for(int i=0; i<RUN_AMOUNT; i++){
            p2 = new Part2();
            counters[i] = p2.bestCounter;
            resultArea.append("RUN " + (i+1));
            resultArea.append("\n----------------------\n");
            for(int j=0; j<6; j++) resultArea.append(p2.population[j].toString() + " --> VALUE: " + p2.population[j].binaryToInt(p2.population[j].toString()) + "   FITNESS: " + p2.population[j].fitness() + "\n");
            resultArea.append("Found in: " + counters[i] + " Generations\n");
            resultArea.append("----------------------\n");
        }
        
        for(int i=0; i<RUN_AMOUNT; i++) sum+=counters[i];
        resultArea.append("Average of " + RUN_AMOUNT + " runs: " + sum / RUN_AMOUNT);
    }//GEN-LAST:event_part2ButtonActionPerformed

    private void tspButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tspButtonActionPerformed
        GA ga = new GA();
        int counter = 0;
        resultArea.setText("");
        while(ga.bestSoFar.fitness() > Integer.parseInt(searchField.getText())){        
        //for(int i=0; i<1000; i++){
            if(counter == Integer.parseInt(stopField.getText())) break;
            ga.generateNextGen();
            if(counter % 10000 == 0){
                resultArea.append("Generation: " + counter +"     Best So Far: " + ga.bestSoFar.fitness() + "    Best This Turn: " + ga.bestThisTurn.fitness());
                resultArea.append("\n--------------------------------------");
                resultArea.append("\nPOPULATION: ");
                resultArea.append("\n--------------------------------------");
                for(int j=0; j<8; j++) resultArea.append("\n" + ga.population[j] + "   --> FITNESS: " + ga.population[j].fitness());
                resultArea.append("\n--------------------------------------\n\n\n\n\n");
            }
            counter++;
        }
        
        resultArea.append("\nBEST:  " + ga.bestSoFar + "    FITNESS: " + ga.bestSoFar.fitness());        
        for(int i=0; i<8; i++) resultArea.append("\n" + ga.population[i] + "   " + ga.population[i].fitness());
        
        resultArea.append("\nTOTAL GENERATIONS: " + counter);
    }//GEN-LAST:event_tspButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("CDE/Motif".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton part2Button;
    private javax.swing.JTextArea resultArea;
    private javax.swing.JTextField runField;
    private javax.swing.JTextField searchField;
    private javax.swing.JTextField stopField;
    private javax.swing.JButton tspButton;
    // End of variables declaration//GEN-END:variables
}
